### ISSUE TITLE
fastApproxMatch no results found

### ISSUE THREAD

**Issue by dgtlmoon** [komrad36/K2NN#3]
Well, atleast it's fast :dancer: 

```
Warming up...
Testing...

Brute force K2NN found 0 matches in 11.2606 ms
Throughput: 8.88049 billion comparisons/second.
```

also, in this case you've switched the methods, so it should not say Brute Force..

`	std::cout << std::endl << "Brute force K2NN found " << m.matches.size() << " matches in " << sec * 1e3 << " ms" << std::endl;
`

**Comment by komrad36** [comment]
Hey! So fastApproxMatch() is, if you check out the description in K2NN.h, a very conservative matcher. It will  only return guaranteed best matches. It only performs a single MIH twiddle. In the demo, it's being fed with random data, so it's not surprising at all that no matches occur. On random 512-bit descriptors the minimum Hamming distance is often >128. In order for fastApproxMatch() to find a match, it'd need to be less than (32 - threshold) distance.

Use full matching with early bailout if you want an extra twiddle pass and approximation, although even at 1 extra pass it's pretty slow. As mentioned in the other thread I'd highly recommend CUDAK2NN, which I spent an enormous amount of time optimizing for the GPU archicture and which blows all prior art out of the water, clocking in at 54 billion comparisons per second on a stock GTX 1080.

Thanks!

**Comment by komrad36** [comment]
Oh, as for the "brute force" text: you're right, but main.cpp, in constrast to K2NN.h, is just a quick-and-dirty demo application and is by no means intended to show good programming practice :D

Compare the amount of documentation to K2NN.h, for example. I just want people to be able to quickly play with it and get timing information.
