### ISSUE TITLE
time problem and right match size 

### ISSUE THREAD

**Issue by Riverhe2014** [komrad36/K2NN#9]
hello! I have run your code,when I use KNN exactMatch metchod and bruteMatch.And I found time using exactMatch is more slower than using  bruteMatch .the other problem is when I use fastApproxMatch to match,and  result is show have no match.Thank you

**Comment by komrad36** [comment]
Hey there! This is not surprising. My results do not suggest that the multi-index hashing technique is faster than brute matching unless the threshold is small AND the number of keypoints is HUGE. For most real-time computer vision solutions, brute matching, especially when done efficiently (see my CUDAK2NN project) is actually much faster.

It's also not surprising that fastApproxMatch can return no matches, depending on your threshold and image. Once again, brute matching is often the way to go, especially if you can use CUDA.

**Comment by Riverhe2014** [comment]
ok，thank you,I will have a try to run your cudak2nn!

**Comment by Riverhe2014** [comment]
hello,I am comming, I have run your cudak2nn with cudaAKAZE, I get the random problem cudaError_t err = err != cudaSuccess I cannot find what is the mater,can you help me? Thank you !
